require("hacker.core.keymaps")
require("hacker.core.packer")
require("hacker.core.set")

require("hacker.plugins.colours")
require("hacker.plugins.filebrowser")
require("hacker.plugins.fugitive")
require("hacker.plugins.harpoon")
require("hacker.plugins.lsp")
require("hacker.plugins.telescope")
require("hacker.plugins.terminal")
require("hacker.plugins.treesitter")
require("hacker.plugins.undotree")
